version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_USER: verifier
      POSTGRES_PASSWORD: truth_is_power
      POSTGRES_DB: verifai_postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    restart: unless-stopped
    networks:
      - tasks

  celery-worker:
    build:
      context: ./
      dockerfile: ./Docker/celery/Dockerfile-celery
    entrypoint: ["/bin/sh", "/code/Docker/celery/worker-entrypoint.sh"]
    volumes:
      - .:/code
    depends_on:
      - postgres
      - redis
    environment:
      - C_FORCE_ROOT=true
    restart: always
    networks:
      - tasks

volumes:
  postgres_data: { }

networks:
  ollama-docker:
  tasks: