# Generated by Django 5.0.3 on 2024-03-21 16:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="fact",
            old_name="content",
            new_name="claim",
        ),
        migrations.RemoveField(
            model_name="fact",
            name="verified",
        ),
    ]
