# Generated by Django 5.0.3 on 2024-04-16 17:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_fact_justification_fact_sources_fact_veracity_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fact",
            name="veracityScore",
        ),
    ]
