"""
Django settings for verifai project.

Generated by 'Cole Agard' using Django 5.0.3.
"""

from pathlib import Path
import environ
import os

env = environ.Env(
    DEBUG=(bool, False),
)
environ.Env.read_env()

root = environ.Path(__file__) - 2
BASE_DIR = root()
print(BASE_DIR)

SECRET_KEY = env('SECRET_KEY')

LLM_ENDPOINT = env.get_value('LLM_ENDPOINT')
ENV_LOCATION = env.get_value('ENV_LOCATION')
DEBUG = env('DEBUG')

ALLOWED_HOSTS = ['*', 'localhost', 'backend-production-3246.up.railway.app']


INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "corsheaders",
    "rest_framework",
    "rest_framework.authtoken",
    "drf_yasg",
    "api",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "verifai.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "verifai.wsgi.application"


DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": env.get_value('POSTGRES_DB'),
        "USER": env.get_value('POSTGRES_USER'),
        "PASSWORD": env.get_value('POSTGRES_PASSWORD'),
        "HOST": env.get_value('POSTGRES_HOST'),
        "PORT": env.get_value('POSTGRES_PORT'),
    },
}


AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

CORS_ALLOW_ALL_ORIGINS = True

CSRF_TRUSTED_ORIGINS = [
    'http://backend-production-3246.up.railway.app',
    'localhost',
    '127.0.0.1'
]

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


STATIC_URL = "static/"

STATIC_ROOT = os.path.join(BASE_DIR, "static")

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

CELERY_BROKER_URL = env.get_value('CELERY_BROKER_URL')
CELERY_RESULT_BACKEND = env.get_value('CELERY_RESULT_BACKEND')
GOOGLE_SEARCH_API_KEY = env.get_value('GOOGLE_SEARCH_API_KEY')
LLM_API_KEY = env.get_value('LLM_API_KEY')
